---
# configure_eth1/tasks/main.yml

- name: 'Load variables'
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"
    - "vars_default.yml"

- name: "create ifcfg-eth1 in {{ ifcfg_location }}"
  ansible.builtin.template:
    src: "templates/ifcfg-eth1.j2"
    dest: "{{ ifcfg_location }}/ifcfg-eth1"
    owner: 'root'
    group: 'root'
    mode: "{{ ifcfg_mode }}"
  notify:
    - 'Set eth1 to down'
    - 'Set eth1 to up'
    - 'Check eth1 settings'
