---
# configure_eth1/handlers/main.yml

- name: 'Set eth1 to down'
  ansible.builtin.command: 'ifdown eth1'

- name: 'Set eth1 to up'
  ansible.builtin.command: 'ifup eth1'

- name: 'Check eth1 settings'
  ansible.builtin.command: 'ip address show eth1'
